@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
UniquePersonList -right-> "*" Person

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> "0..1" TeleHandle
Person *--> StudentId
Person *--> TutorialGroup
Person *--> Attendance

Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> TeleHandle
TeleHandle -[hidden]right-> StudentId
StudentId -[hidden]right-> TutorialGroup
TutorialGroup -[hidden]right-> Attendance
@enduml
